export const mockData = [
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'H',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'H',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'M',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'L',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'H',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'M',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'L',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'M',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'H',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
  {
    customer: 'Bimbo',
    location: 'New York',
    line: '1',
    station: 'Station 1',
    product: 'All',
    objectType: 'Localization',
    priority: 'L',
    noofimg: '1270',
    uploaded: '27.04.2020 11:40pm',
    assignedBy: 'I.Anthony',
    status: 'Not started',
  },
];

export const mockHeaders = [
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  ['Customer', 'Location', 'Line', 'Station /Oven Type', 'Product'],
  [
    'Customer',
    'Location',
    'Line',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  ['Priority', 'No of Img', 'Uploaded on', 'Assignment By', 'Status'],
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  ['No of image'],
  ['Uploaded on'],
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
  [
    'Customer',
    'Location',
    'Line',
    'Station /Oven Type',
    'Product',
    'Object Type',
    'Priority',
    'No of Img',
    'Uploaded on',
    'Assignment By',
    'Status',
  ],
];

// export const mockHeaders = [
// {
//   customer: ['Customer', 'Location', 'Line', 'Station /Oven Type', 'Product', 'Object Type', 'Priority','No of Img', 'Uploaded on','Assignment By','Status']
// },
// {

// }
// ]

export const sample = [
  {
    key: 'sss',
    name: 'ssssss',
    id: 0,
  },
  {
    key: 'sss',
    name: 'ssssss',
    id: 1,
  },
  {
    key: 'sss',
    name: 'ssssss',
    id: 2,
  },
];
